```
[silly] question for the slack bot experts: in many examples I keep seeing a variable named BOT_ID, what is this ID? All I get from slack is the bot token
that's not a silly question. It's the id of your bot that slack return when you use <https://api.slack.com/methods/rtm.connect>
or `rtm.start` it's useful to filter message coming from your bot
but normally they shouldn't need it as they can easily retrieve it for you
this is a pretty basic questions - but when an exception is thrown the rest of the code after where the exception occurred is not executed unless it was handled in a `try` `except`?
I'm deciding whether I should test code with a context manager of an object that throws an exception, although I don't think I am correct in the what happens
yes. you can add a `finally` if you want a piece of code to always be executed
it depends on the what but in some case it can overlapp yes
so let's say that's the code and we're expecting a new_object to be created based on the paramteters, but an exception can occur like a URLError or something
what I'm trying to do is test the correct exception is thrown/handled
so I was thinking...
`as new_object` looks strange to me
If you are testing code I believe both pytest and unitest have special context manager to test errors
